services:
  - type: web
    name: jobworld
    runtime: node
    buildCommand: |
      npm install --production=false
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"